package activity.liuxing.tv.com.tvliuxing.activity.entity;

import java.io.Serializable;
import java.math.BigDecimal;


public class RedSignNew implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.id
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.account_id
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.year
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.month
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.day
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.sign_type
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.record_message
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private String recordMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.sign_money
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private BigDecimal signMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.is_delete
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.is_check_sign
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer isCheckSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.is_sign
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer isSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.create_time
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_sign_new.update_time
     *
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.id
     *
     * @return the value of red_sign_new.id
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    private String signAwardMessage;

    private BigDecimal signAwardMoney;            //签到获取的金额

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.id
     *
     * @param id the value for red_sign_new.id
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.account_id
     *
     * @return the value of red_sign_new.account_id
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.account_id
     *
     * @param accountId the value for red_sign_new.account_id
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.year
     *
     * @return the value of red_sign_new.year
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.year
     *
     * @param year the value for red_sign_new.year
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.month
     *
     * @return the value of red_sign_new.month
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.month
     *
     * @param month the value for red_sign_new.month
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.day
     *
     * @return the value of red_sign_new.day
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.day
     *
     * @param day the value for red_sign_new.day
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.sign_type
     *
     * @return the value of red_sign_new.sign_type
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.sign_type
     *
     * @param signType the value for red_sign_new.sign_type
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setSignType(Integer signType) {
        this.signType = signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.record_message
     *
     * @return the value of red_sign_new.record_message
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public String getRecordMessage() {
        return recordMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.record_message
     *
     * @param recordMessage the value for red_sign_new.record_message
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setRecordMessage(String recordMessage) {
        this.recordMessage = recordMessage == null ? null : recordMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.sign_money
     *
     * @return the value of red_sign_new.sign_money
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public BigDecimal getSignMoney() {
        return signMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.sign_money
     *
     * @param signMoney the value for red_sign_new.sign_money
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setSignMoney(BigDecimal signMoney) {
        this.signMoney = signMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.is_delete
     *
     * @return the value of red_sign_new.is_delete
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.is_delete
     *
     * @param isDelete the value for red_sign_new.is_delete
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.is_check_sign
     *
     * @return the value of red_sign_new.is_check_sign
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getIsCheckSign() {
        return isCheckSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.is_check_sign
     *
     * @param isCheckSign the value for red_sign_new.is_check_sign
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setIsCheckSign(Integer isCheckSign) {
        this.isCheckSign = isCheckSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.is_sign
     *
     * @return the value of red_sign_new.is_sign
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getIsSign() {
        return isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.is_sign
     *
     * @param isSign the value for red_sign_new.is_sign
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setIsSign(Integer isSign) {
        this.isSign = isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.create_time
     *
     * @return the value of red_sign_new.create_time
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.create_time
     *
     * @param createTime the value for red_sign_new.create_time
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_sign_new.update_time
     *
     * @return the value of red_sign_new.update_time
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_sign_new.update_time
     *
     * @param updateTime the value for red_sign_new.update_time
     * @mbggenerated Fri Jun 24 11:00:40 CST 2016
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    public String getSignAwardMessage() {
        return signAwardMessage;
    }

    public void setSignAwardMessage(String signAwardMessage) {
        this.signAwardMessage = signAwardMessage;
    }

    public BigDecimal getSignAwardMoney() {
        return signAwardMoney;
    }

    public void setSignAwardMoney(BigDecimal signAwardMoney) {
        this.signAwardMoney = signAwardMoney;
    }

    @Override
    public String toString() {
        return "RedSignNew [id=" + id + ", accountId=" + accountId + ", year="
                + year + ", month=" + month + ", day=" + day + ", signType="
                + signType + ", recordMessage=" + recordMessage
                + ", signMoney=" + signMoney + ", isDelete=" + isDelete
                + ", isCheckSign=" + isCheckSign + ", isSign=" + isSign
                + ", createTime=" + createTime + ", updateTime=" + updateTime
                + ", signAwardMessage=" + signAwardMessage
                + ", signAwardMoney=" + signAwardMoney + "]";
    }


}